SET FOREIGN_KEY_CHECKS = 0; # SET KEY CHECKS TO 0 SO AS TO AVOID FOREIGN KEY CONSTRAINTS CAUSING PROBLEMS WHEN DROPPING TABLES
DROP TABLE IF EXISTS wp_trench_access;
DROP TABLE IF EXISTS wp_trench_product;
DROP TABLE IF EXISTS wp_trench_cust_options;
DROP TABLE IF EXISTS wp_trench_filter_options;
DROP TABLE IF EXISTS wp_trench_grille_prices;
DROP TABLE IF EXISTS wp_trench_heat_constants;
DROP TABLE IF EXISTS wp_trench_elec_output;
DROP TABLE IF EXISTS wp_trench_hc_output;
SET FOREIGN_KEY_CHECKS = 1;

#HOLDS ALL ACCESSORIES FOR TRENCH PRODUCTS
CREATE TABLE IF NOT EXISTS wp_trench_access (
    accessID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    accessName VARCHAR(255) NOT NULL,
    compatAccess VARCHAR(20) NOT NULL
)ENGINE=INNODB;

#PRIMARY TABLE FOR LISTED PRODUCTS
CREATE TABLE IF NOT EXISTS wp_trench_product (
    productID VARCHAR(100) PRIMARY KEY,
    modelName VARCHAR(100) NOT NULL,
    basePrice VARCHAR(20) NOT NULL,
    length VARCHAR(100) NOT NULL,
    width VARCHAR(100) NOT NULL,
    depth VARCHAR(100) NOT NULL
)ENGINE=INNODB;

#CUSTOMISATION OPTIONS CHOSEN PRIOR TO SPECIFICATION
CREATE TABLE IF NOT EXISTS wp_trench_cust_options (
    optionID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    optionName VARCHAR(255) NOT NULL,
    optionText VARCHAR(255) NOT NULL,
    custID VARCHAR(20) NOT NULL,
    pricePercentage VARCHAR(50)
)ENGINE=INNODB;

#FILTER OPTIONS
CREATE TABLE IF NOT EXISTS wp_trench_filter_options (
    optionID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    compatOption VARCHAR(100) NOT NULL,
    optionText VARCHAR(200) NOT NULL,
    optionID VARCHAR(100) NOT NULL
)ENGINE=INNODB;

#PRICES FOR GRILLES
CREATE TABLE IF NOT EXISTS wp_trench_grille_prices (
    priceID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    grilleLength VARCHAR(20) NOT NULL,
    grilleID VARCHAR(100) NOT NULL,
    grillePrice VARCHAR(20) NOT NULL,
    grilleElectric VARCHAR(20) NOT NULL
)ENGINE=INNODB;

#HEAT OUTPUT CONSTANTS FOR CALCULATION
CREATE TABLE IF NOT EXISTS wp_trench_heat_constants (
    productID VARCHAR(100) PRIMARY KEY,
    heatOutputConstOne VARCHAR(50) NOT NULL,
    heatOutputConstTwo VARCHAR(50) NOT NULL,
    heatOutputConstThree VARCHAR(50) NOT NULL,
    FOREIGN KEY (productID) REFERENCES trench_product(productID)
)ENGINE=INNODB;

#OUTPUT FOR ELECTRIC PRODUCTS
CREATE TABLE IF NOT EXISTS wp_trench_elec_output (
    productID VARCHAR(100) PRIMARY KEY,
    heatOutput VARCHAR(100) NOT NULL,
    FOREIGN KEY (productID) REFERENCES trench_product(productID)
)ENGINE=INNODB;

#OUPUT FOR HEATING AND COOLING PRODUCTS
CREATE TABLE IF NOT EXISTS wp_trench_hc_output (
    productID VARCHAR(100) PRIMARY KEY,
    heatOutput VARCHAR(100) NOT NULL,
    coolOutput VARCHAR(100) NOT NULL,
    FOREIGN KEY (productID) REFERENCES trench_product(productID)
)ENGINE=INNODB;